/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { UserService } from "../user.service";
import { UserCreateInput } from "./UserCreateInput";
import { User } from "./User";
import { UserFindManyArgs } from "./UserFindManyArgs";
import { UserWhereUniqueInput } from "./UserWhereUniqueInput";
import { UserUpdateInput } from "./UserUpdateInput";
import { DailydatumFindManyArgs } from "../../dailydatum/base/DailydatumFindManyArgs";
import { Dailydatum } from "../../dailydatum/base/Dailydatum";
import { DailydatumWhereUniqueInput } from "../../dailydatum/base/DailydatumWhereUniqueInput";

export class UserControllerBase {
  constructor(protected readonly service: UserService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: User })
  async createUser(@common.Body() data: UserCreateInput): Promise<User> {
    return await this.service.createUser({
      data: {
        ...data,

        task: data.task
          ? {
              connect: data.task,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        email: true,
        finance: true,
        fullname: true,
        id: true,
        phone: true,

        task: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        vision: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [User] })
  @ApiNestedQuery(UserFindManyArgs)
  async users(@common.Req() request: Request): Promise<User[]> {
    const args = plainToClass(UserFindManyArgs, request.query);
    return this.service.users({
      ...args,
      select: {
        createdAt: true,
        email: true,
        finance: true,
        fullname: true,
        id: true,
        phone: true,

        task: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        vision: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async user(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    const result = await this.service.user({
      where: params,
      select: {
        createdAt: true,
        email: true,
        finance: true,
        fullname: true,
        id: true,
        phone: true,

        task: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        vision: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateUser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() data: UserUpdateInput
  ): Promise<User | null> {
    try {
      return await this.service.updateUser({
        where: params,
        data: {
          ...data,

          task: data.task
            ? {
                connect: data.task,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          email: true,
          finance: true,
          fullname: true,
          id: true,
          phone: true,

          task: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
          vision: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteUser(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    try {
      return await this.service.deleteUser({
        where: params,
        select: {
          createdAt: true,
          email: true,
          finance: true,
          fullname: true,
          id: true,
          phone: true,

          task: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
          vision: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/dailydata")
  @ApiNestedQuery(DailydatumFindManyArgs)
  async findDailydata(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<Dailydatum[]> {
    const query = plainToClass(DailydatumFindManyArgs, request.query);
    const results = await this.service.findDailydata(params.id, {
      ...query,
      select: {
        createdAt: true,
        date: true,
        daydata: true,
        finance: true,
        id: true,
        note: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/dailydata")
  async connectDailydata(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: DailydatumWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      dailydata: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/dailydata")
  async updateDailydata(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: DailydatumWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      dailydata: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/dailydata")
  async disconnectDailydata(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: DailydatumWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      dailydata: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }
}
